### ISSUE TITLE
Data format / rosbag sample

### ISSUE THREAD

**Issue by zhukovv** [EliaTarasov/ESKF#1]
Hello,

thank you for sharing this very useful tool!

Could you please advice which data should be fed for proper operation - I tried KITTI datasets, as well as my own data, taken from a mobile device, but all I've got is a constant drift in resulting position, by one or two axes.

**Comment by EliaTarasov** [comment]
@zhukovv  hello!
You need local position and orientation measurements according to [REP 103](http://www.ros.org/reps/rep-0103.html) format.

**Comment by zhukovv** [comment]
@EliaTarasov OK, thank you!

**Comment by bryantaoli** [comment]
Can you just give us some rosbag you test this code? Maybe some small rosbag.
